### ISSUE TITLE
Perfil de Coach

### ISSUE THREAD

**Issue by apolobra** [apolobra/poker-coach-2#10]
Esta autorização precisa estar no SuperAdmin, os dados precisam ser visualizados e aprovados ou reprovados.

**Aprovados**: Recebem um e-mail + notificação que foi aprovado o cadastro e vai para o cadastro de aulas.

**Reprovados**: Recebem e-mail + notificação e os dados cadastrados serão limpos

**Comment by igordnt** [comment]
São esses passos mesmo. Vou retirar o passo do Pacote de Aulas do Cadastro de Coach e trocar a aba "Compras" por "Aulas". Inclusive, no email de notificação dos coaches, aqueles que forem aprovados, seria legal ter um call to action que levasse para as aulas. Algo do tipo "Parabéns, agora vc já pode montar seus pacotes de aulas. [montar pacote de aulas]"

**Comment by apolobra** [comment]
Certo! 

Status do coach dentro da tabela jogadores_parametros
coach = [ true, false, pending ]

Se ele for TRUE para coach, pode criar aulas e o botão do topo deve ir para aulas
Se ele for FALSE para coach, o formulário em 3 etapas aparecerão e precisa ser concluído para então entrar em status de pending.
Se ele for PENDING aparece para o SuperAdmin esse jogador em evidência para que ele visualize os dados e o libere.

**Comment by igordnt** [comment]
Segue abaixo os sites a serem inseridos no combo box da parte de "estatísticas":

- SharkScope
- Top Shark Pro
- Official Poker Rankings
- The Hendon Mob
- High Stakes DB

**Comment by apolobra** [comment]
@igordnt 
Qual é a relação de sites de poker?

**Comment by apolobra** [comment]
Editar foto principal do perfil, mudar o formato da mascara.

**Comment by apolobra** [comment]
- [ ] Tirar o campo de CPF
- [ ] Apelido vira obrigatório com validação

**Comment by igordnt** [comment]
Relação de sites:

1- PokerStars
2- 888poker
3- Bodog
4- Winamax
5- PartyPoker
6- WSOP
7- Titan Poker
8- American Card Room
9- Black Chip Poker
10- William Hill
12- NetBet
13- Bet 365
14- Betfair
15- Everest Poker
16- Coral
17- YaPoker

**Comment by apolobra** [comment]
[ ] No menu principal quando estiver dentro do formulário de coach em qualquer estágio nada pode ficar marcado.
