### ISSUE TITLE
Feed principal do dashboard

### ISSUE THREAD

**Issue by apolobra** [apolobra/poker-coach-2#11]
Também é possível dentro de um feed ser curtido e comentado por outros jogadores. Ele apenas vê feed dos seus jogadores favoritos.

**Comment by igordnt** [comment]
Ele vê feed de jogadores favoritos, feed do usuário do site e feed de propagandas.

**Comment by apolobra** [comment]
![captura de tela 2016-02-07 as 11 23 50](https://cloud.githubusercontent.com/assets/17006402/12872558/67b51cde-cd8d-11e5-9bc7-3a4294fa9466.png)

**Comment by igordnt** [comment]
Apolo, estava pensando aqui e acho que deveríamos a tag "Cotidiano" por "Notícias".

Quem quiser postar coisa off-topic deixa sem tag mesmo. O que acha?

**Comment by apolobra** [comment]
Comentários do feed são simples. 
- [ ] após submit do comentário enviar uma notificação para o dono do post
- [ ] apagar comentários o dono do post e o dono do comentário

Curtir
- [ ] apenas uma curtida por usuário por post
- [ ] clicar novamente no post curtido, ele deixa de curtir

Imagem
- [ ] fazer upload da imagem

Cores das tags
- [ ] gravar código de cores da cada tag @igordnt 

Visualização de feeds
- [ ] visualizar 12 cards
- [ ] ao rolar a página automaticamente carrega novos cards

**Comment by igordnt** [comment]
Segue o hex das tags:
- Coach: 0080ca
- Promoção: 662d91
- Dicas: 754c24
- Resultados: 09bb00
- Notícia: bf360c

**Comment by apolobra** [comment]
- [ ] Filtrar por feed tag

**Comment by apolobra** [comment]
Output:
![captura de tela 2016-03-18 as 09 16 54](https://cloud.githubusercontent.com/assets/17006402/13877696/43f8df74-eceb-11e5-834a-acf751076ed9.png)
![captura de tela 2016-03-18 as 09 17 43](https://cloud.githubusercontent.com/assets/17006402/13877697/43f91516-eceb-11e5-8f99-a74ddcb2ab7e.png)
![captura de tela 2016-03-18 as 09 00 37](https://cloud.githubusercontent.com/assets/17006402/13877698/43fa3374-eceb-11e5-9308-5abe2cb4cf89.png)

**Comment by apolobra** [comment]
Novo feed
- [x] iterações com a imagem
- [x] iteração de abrir a bandeja com botão Publicar ao acessar o testarem
- [x] expandir o textarea conforme há digitação de texto
- [x] escolher uma tag opcional e depois ela aparecer como selecionada

**Comment by apolobra** [comment]
Output form sem iteração nenhuma:
![captura de tela 2016-03-19 as 19 14 44](https://cloud.githubusercontent.com/assets/17006402/13901569/39ebb246-ee07-11e5-8b49-53b89926ea9f.png)

Confirmação visual da escolha da foto, após o usuário escolher a foto o ícone da câmera fica verde sinalizando que existe uma foto já adicionada.
![captura de tela 2016-03-19 as 19 13 29](https://cloud.githubusercontent.com/assets/17006402/13901599/fa54e61a-ee07-11e5-8ea7-103f2f1e19da.png)
![captura de tela 2016-03-19 as 19 13 23](https://cloud.githubusercontent.com/assets/17006402/13901598/fa1534f2-ee07-11e5-8c52-5171aa2045a4.png)

**Comment by apolobra** [comment]
Output dos comentários:
![captura de tela 2016-03-20 as 12 00 34](https://cloud.githubusercontent.com/assets/17006402/13905076/192b10fa-ee94-11e5-89a1-b82761d11366.png)

**Comment by apolobra** [comment]
- [ ] Apagar comentários o dono do post e o dono do comentário
- [ ] Filtrar por Feed tag
- [ ] Ao adicionar uma foto trocar o ícone por um clips e colocar "Foto anexada".

**Comment by apolobra** [comment]
![captura de tela 2016-04-16 as 08 43 27](https://cloud.githubusercontent.com/assets/17006402/14580773/5f554160-03af-11e6-8432-0ca9440fff3d.png)
