### ISSUE TITLE
Erros no Feed (Novidades)

### ISSUE THREAD

**Issue by igordnt** [apolobra/poker-coach-2#30]
- [x] Novos posts não estão aparecendo
- [x]  Cards estão desalinhados

**Comment by apolobra** [comment]
Novos posts aparecem se a tag dele está selecionada no filtro selecionado para exibir. Desta forma os sem tag nunca aparecem.

**Comment by apolobra** [comment]
output:
![captura de tela 2016-05-07 as 08 57 15](https://cloud.githubusercontent.com/assets/17006402/15091961/d3d9ff48-1431-11e6-9376-901dc33f60dc.png)
