### ISSUE TITLE
Perfil de Coach (Jogador)

### ISSUE THREAD

**Issue by apolobra** [apolobra/poker-coach-2#4]
Botão "Torne-se um Coach" fica no menu principal no canto direito após o efetuar o login.
- [x] colocar botão no html
- [x] marcação no cadastro do jogador se já completou esse cadastro ou não
- [x] caso não esteja completo, continuar apresentando o botão "Torna-se um Coach"
- [x] editar as informações dentro do perfil (abas)
- [ ] criar estrutura bd de sites + urls

**Comment by apolobra** [comment]
@gifs88 Por que existem salas e screen name no perfil do jogador (coach), poderia me explicar?
 
![captura de tela 2016-02-01 as 15 02 54](https://cloud.githubusercontent.com/assets/17006402/12724428/1343ea6e-c8f5-11e5-8ec3-e97340bafc5e.png)

**Comment by gifs88** [comment]
O jogador pode ter conta em diversos sites de poker (Poker Stars, Full Tilt, 888, Titan Poker, etc.), e em cada uma dessas salas pode ter um screen name diferente. Por exemplo: no Poker Stars posso por o screen name gifs88 e no Full Tilt gifs1706.

Pra jogadores de campeonatos, é muito comum ter conta em diversos sites diferentes.

**Comment by apolobra** [comment]
Ok, ótimo! Existe uma listagem com esses sites que vamos aceitar? Vou colocar no cadastro de cada site então, Nome, URL e Ícone do site.

**Comment by igordnt** [comment]
http://www.pokerscout.com/

Aqui tem todas as salas disponíveis Apolo.

**Comment by apolobra** [comment]
Perfil de Coach precisa de moderação e um status de aguardando! Para que não haja outro cadastro.

**Comment by apolobra** [comment]
Se o usuário tiver um perfil em aprovação colocar a tela de confirmação para aguardar.
