### ISSUE TITLE
Kerpo.co - 1.3

### ISSUE THREAD

**Issue by apolobra** [apolobra/poker-coach-2#52]
- [x] eliminar o menu favoritos/seguir/seguidores
- [x] eliminar parte de aulas
- [x] em mensagens, eliminar o pesquisar
- [x] eliminar botão "Crie uma aula"
- [x] qualquer usuário pode colocar vídeo
- [x] header Buscar, Menu Explorar, Notificações e Mensagens serão eliminados
- [x] header: o Menu é o mesmo da Home
- [x] Em novidades apenas administrador pode postar

**Comment by apolobra** [comment]
https://marvelapp.com/2b37j84#12260189 - vídeo.

**Comment by igordnt** [comment]
Link do novo protótipo: https://marvelapp.com/196873h
