### ISSUE TITLE
Bugs - Upload Vídeo

### ISSUE THREAD

**Issue by igordnt** [apolobra/poker-coach-2#53]
Teste #1 - Arquivos .JPEG
1- Consegui enviar um .JPEG no box de arquivos para vídeos e o sistema aceitou;
2- Enviei um thumbnail .JPEG, mas não funcionou (o arquivo de imagem aparece vazio);
3- CloudConverter processou um .JPEG com sucesso e me confirmou as conversões (wtf?).

Teste #2 - Envio sem confirmação
1- Deu 100% mas não apareceu a janela de "Upload realizado com sucesso". Mesmo assim consegui enviar e apareceu a tela de envio com sucesso;
2- Thumbnail em .PNG funcionou.

Teste #3- Substituição de arquivo
1- Substituição de arquivos está OK;
2- Cancelar o envio está OK;
3- Deu 100% mas não confirmou o upload, de novo;
4- Consegui enviar um arquivo sem Thumbnail (não deveria poder)

Teste #4 - Arquivo errado
1- Consegui fazer upload de vários arquivos de vídeo em um único envio;
2- Consegui enviar vários thumbnails diferentes em único envio;

**Comment by igordnt** [comment]
Correções e bugs:

- [ ] Precisa de um botão de excluir vídeo, tanto para o usuário quanto para o administrador;
- [ ] O administrador precisa de um botão de Editar para os vídeos também;
- [ ] Aguardando processar leva para Aguardando publicação, no painel administrativo;
- [ ] Thumbnails em .JPEG não funcionam;
- [ ] As combo boxes estão vazias (suspeito que seja em relação ao formato do box, o formato do Idioma está com os cantos arredondados e funcionando. As outras estão com os cantos quadrados e não funcionam);
- [ ] Formulário de envio de vídeo deve ser separado em dois.

**Comment by igordnt** [comment]
Link do vídeo de testes: https://youtu.be/GIEXRQ2pEkk

**Comment by apolobra** [comment]
Status dos vídeos:
A = VIDEO ESTÁ ATIVO/PUBLICADO/CIRCULANDO NO SITE

I = INATIVO, porém pode torna-se ATIVO

PR_CC = PROCESSANDO NO CLOUD CONVERT

P = PENDENTE PARA PROCESSAR O VIDEO, SEM ARQUIVO DO VÍDEO. BOTÃO DE PROCESSAR NÃO APARECE SE NÃO HOUVER O ARQUIVO.

L = ARQUIVO FOI PROCESSADO PELO CLOUDCONVERT, MAS PRECISA SER PUBLICADO PELO ADMIN, CONFERIDO. QUANDO O ADMIN PUBLICA O VÍDEO, ELE PASSA PARA STATUS "A" E O CONTROLE PASSA A SER DO JOGADOR TAMBÉM, SOBRE PAUSA OU EDIÇÃO.
