### ISSUE TITLE
Os perfis criam as mensagem e elas aparecem no feed dos usuários

### ISSUE THREAD

**Issue by apolobra** [apolobra/poker-coach-2#6]
Este feed criado pelo usuário pode ter uma imagem (foto), texto e uma tag específica. Cotidiano, Coach, Promoções, Dicas e Resultados.

**Comment by igordnt** [comment]
Tags por ordem que devem aparecer no combo box:
- Coach
- Promoção
- Dicas
- Resultados
- Cotidiano

Há também a possibilidade do usuário não botar tag.
