### ISSUE TITLE
Modalidade, Tipos de jogo e Stakes

### ISSUE THREAD

**Issue by apolobra** [apolobra/poker-coach-2#8]
Modalidades do Poker:
- SNG (Sit and Go)
- MTT (Multi Table Tournament)
- Cash Games

Dentro de cada modalidade existem tanto as variantes do poker
quanto os stakes:

Tipo de jogos
- Texas Hold'Em
- Omaha Hi
- Omaha Hi/Lo
- Razz
- Stud Hi
- Stud Hi/Lo
- 5 Card Stud
- Draw Poker

Dentro dessas variantes existem os stakes, que são os limites (em
termos monetários) que as pessoas jogam: Dá pra descrever de forma
mais precisa mas acho que pode definir como:

- Micro Stakes ($0,00 a $5,00)
- Low Stakes ($5,01 a $30,00)
- Medium Stakes ($30,01 a $100,00)
- High Stakes ($100,01+)

@igordnt é isso?

**Comment by igordnt** [comment]
Vamos lá. Tipo de jogo e Modalidade estão trocados. Então segue abaixo o correto.

Quando o coach for cadastrar o que ele joga, devem aparecer 3 combo boxes para ele.

A primeira combo box é de "Modalidade", onde ele terá as opções:
- Texas Hold'Em
- Omaha Hi
- Omaha Hi/Lo
- Razz
- Stud Hi
- Stud Hi/Lo
- 5 Card Stud
- Draw Poker
- Open-Face Chinese
- Badugi

(Existem mais modalidades, mas vamos começar com essas e acrescentamos mais de acordo com a necessidade)

A segunda combo box é de "Tipo de jogo". Que seriam:
- SNG (Sit and Go)
- MTT (Multi-table tournament)
- Cash Games
 
A terceira combo box deve ser dinâmica e mudar de acordo com a opção escolhida na segunda combo box.

Para Sit and Go, ela deve ser:
- Double or Nothing ou Fifty50
- 9 Max Regular
- 9 Max Turbo
- 9 Max Hyper Turbo
- 6 Max Regular
- 6 Max Turbo
- 6 Max Hyper Turbo
- Heads up Regular
- Heads up Turbo
- Heads up Hyper Turbo

Para MTT ela deve ser:
- Todos
- 180 jogadores
- 90 jogadores
- 45 jogadores
- 18 jogadores

e para Cash Games deve ser:
- Full Ring
- 6-handed
- Heads up
- Zoom, Rush, Speed

Depois que ele escolher a variante que irá jogar, ele deve escolher o stake, o combo box do stake deve ser:
- Todos os stakes
- Micro Stakes ($0,00 a $5,00)
- Low Stakes ($5,01 a $30,00)
- Medium Stakes ($30,01 a $100,00)
- High Stakes ($100,01+)

**Comment by igordnt** [comment]
Apolo, esqueci de mencionar uma modalidade importantíssima.

Dentro de Sit and Go, você deve incluir o seguinte tipo de jogo:

- Spin and Go

**Comment by igordnt** [comment]
Consertar em "Tipo de jogo":
- [ ] De "Cash Games" para "Cash Game"
- [ ] De "MTT (Multi-table tournament)" para "MTT (Multi-Table Tournament)"

Consertar em "Sit and Go":
- [ ] De "Heads up Regular" para "Heads Up Regular"
- [ ] De "Heads up Turbo" para "Heads Up Turbo"
- [ ] De "Heads up Hyper Turbo" para "Heads Up Hyper Turbo"

Consertar em "Cash Game":
- [ ] De "Heads up" para "Heads Up"
